PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix mods: <http://www.loc.gov/mods/rdf/v1#>
prefix mads: <http://www.loc.gov/mads/rdf/v1#>
prefix ht: <http://hathitrust.org/htrc/workset#> 
prefix prov: <http://www.w3.org/ns/prov#> 
prefix ore: <http://www.openarchives.org/ore/terms/> 
prefix ro: <http://purl.org/wf4ever/ro#> 
prefix ao: <http://purl.org/ontology/ao/core#> 
prefix eeboo: <http://eeboo.oerc.ox.ac.uk/eeboo/>
PREFIX salt: <http://eeboo.oerc.ox.ac.uk/salt/>
PREFIX saltset: <http://eeboo.oerc.ox.ac.uk/saltsets/>
PREFIX bib: <http://id.loc.gov/ontologies/bibframe>
PREFIX : <http://eeboo.oerc.ox.ac.uk/>

INSERT {{
	GRAPH :worksets {{ 
	   {workseturi}
			a owl:NamedIndividual ;
			a ht:Workset ;
			dc:created {created} ;
			dc:modified {modified} ;
			dc:title {title} ;
			dc:creator {user} ;
			a ro:ResearchObject ;
			a ore:Aggregation ;
			ore:aggregates ?work ; 
			ht:gathers ?work ;
			dc:abstract {abstract} .
	}}
}} 
WHERE {{
   VALUES ?work {{
		{works}
   }}
}}
