PREFIX saltset: <http://eeboo.oerc.ox.ac.uk/saltsets/>
PREFIX salt: <http://eeboo.oerc.ox.ac.uk/salt/>
PREFIX : <http://eeboo.oerc.ox.ac.uk/>

select distinct ?uri ?label { 
  { 
     ?uri salt:in_salt_set saltset:eeboo_creators ; 
        rdfs:label ?label .
  }
  UNION { 
     ?uri salt:in_salt_set saltset:htrc-wcsa_creators;
        rdfs:label ?label .
     MINUS {
          ?uri :matchParticipant ?match .
          ?foo :matchParticipant ?match ; 
               salt:in_salt_set saltset:eeboo_creators . 
     } .
  }
}
