PREFIX saltset: <http://eeboo.oerc.ox.ac.uk/saltsets/>
PREFIX salt: <http://eeboo.oerc.ox.ac.uk/salt/>
PREFIX eeboo: <http://eeboo.oerc.ox.ac.uk/>
PREFIX : <http://eeboo.oerc.ox.ac.uk/>

select distinct ?place { 
  { 
     ?work salt:in_salt_set saltset:eeboo_works ; 
        eeboo:raw_pubplace ?place .
  }
  UNION { 
     ?work salt:in_salt_set saltset:htrc-wcsa_works;
           <http://www.loc.gov/mods/rdf/v1#placeOfOrigin>  ?placeNode .

        ?placeNode a <http://www.loc.gov/mads/rdf/v1#Geographic>;
                             rdfs:label ?place .
  }
}
order by ?place
