PREFIX ht: <http://hathitrust.org/htrc/workset#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX mods: <http://www.loc.gov/mods/rdf/v1#>
PREFIX salt: <http://eeboo.oerc.ox.ac.uk/salt/>
PREFIX eeboo: <http://eeboo.oerc.ox.ac.uk/eeboo/>
SELECT DISTINCT ?workset ?uri ?urilocal ?mod_date ?title ?abstract ?username ?work ?worktitle ?author ?creator ?pubdate ?datePrecision ?place ?imprint ?elecLoc ?viaf ?loc ?saltset 
WHERE {{
    {0}
    {1}
    ?workset a ht:Workset ;
       dc:modified ?mod_date ;
       dc:title ?title ;
       dc:abstract ?abstract ;
       dc:creator ?username ;
       ht:gathers ?work .
#    ?user dc:identifier ?username .
    ?work salt:in_salt_set ?saltset .
    OPTIONAL {{ 
        ?work rdfs:label ?worktitle; 
              eeboo:raw_pubplace ?place ;
              eeboo:creator ?creator .
        ?creator rdfs:label ?author . 
        ?work mods:publisher ?publisherbnode .
        ?publisherbnode rdfs:label ?publisher .
        BIND(COALESCE(?publisher, "") as ?imprint) .
        ?work eeboo:electronicLocation ?elecLoc .
        OPTIONAL {{ 
           ?creator eeboo:hasExternalAuthorityVIAF ?viafid .
           ?creator eeboo:hasExternalAuthorityLoC ?locid .
        }}
        BIND(COALESCE(?viafid, "") as ?viaf) .
        BIND(COALESCE(?locid, "") as ?loc) .
        OPTIONAL {{ 
            ?work eeboo:precise-publication ?precisepub .
            BIND("" as ?pubDatePrecision) . 
        }}
        OPTIONAL {{ 
            ?work eeboo:approx-publication ?approxpub .
            BIND("(approx.)" as ?pubDatePrecision) .
        }}
    
        BIND(COALESCE(STR(COALESCE(?precisepub, ?approxpub)), "Unknown") as ?pubdate ).
        BIND(COALESCE(?pubDatePrecision, "") as ?datePrecision) . 

     
    }}  . 
    OPTIONAL{{ 
        ?work mods:resourceDateIssued ?pubdate .
        FILTER(str(datatype(?pubdate)) = "xsd:string") . 
        ?work mods:titlePrincipal ?titlebnode ;
                mods:placeOfOrigin ?placebnode .
        ?placebnode rdfs:label ?place . 
        FILTER(?place != "enk" && ?place != "stk") . #TODO what is this?
        ?titlebnode rdfs:label ?worktitle .
        FILTER(?worktitle != "ESTC" && ?worktitle != "Wing (2nd ed.)" && ?worktitle != "Wing (2nd ed., 1994)") . #TODO what are these?
        ?work  dc:creator ?creator ;
                mods:statementOfResponsibility ?publisher;
                mods:locationOfResource ?locbnode1 .
        BIND(COALESCE(?publisher, "") as ?imprint) .
        ?locbnode1 mods:locationCopy ?locbnode2 .
        ?locbnode2 mods:locationCopyElectronicLocator ?elecLocStr .
        BIND(IRI(?elecLocStr) as ?elecLoc) .
        ?creator rdfs:label ?author .
        BIND("" as ?datePrecision) .
        BIND("" as ?viaf) .
        BIND("" as ?loc) .
              
    }} .
}}

