PREFIX saltset: <http://eeboo.oerc.ox.ac.uk/saltsets/>
PREFIX salt: <http://eeboo.oerc.ox.ac.uk/salt/>
PREFIX : <http://eeboo.oerc.ox.ac.uk/>

select distinct ?uri ?label {
  {  
        ?uri salt:in_salt_set ?saltset .
        VALUES ?saltset {
                saltset:eeboo_creators
                saltset:htrc-wcsa_creators
        } .
        ?uri rdfs:label ?label .
  }
  MINUS {
        ?uri salt:in_salt_set saltset:htrc-wcsa_creators ;
                :matchParticipant ?match .
        ?eeuri salt:in_salt_set saltset:eeboo_creators ;
                :matchParticipant ?match
  }
}
ORDER BY ?label 

