PREFIX ht: <http://hathitrust.org/htrc/workset#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX mods: <http://www.loc.gov/mods/rdf/v1#>
PREFIX salt: <http://eeboo.oerc.ox.ac.uk/salt/>
PREFIX eeboo: <http://eeboo.oerc.ox.ac.uk/eeboo/>
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>

select ?saltset ?workset ?creator ?mod_date ?title ?abstract ?username ?work ?instance ?item ?author ?publisher ?place ?pubdate ?worktitle
where {{
		{1}
    ?workset a ht:Workset ;
       dc:modified ?mod_date ;
       dc:title ?title ;
       dc:abstract ?abstract ;
       dc:creator ?username ;
       ht:gathers ?work .
     {{
     ?work salt:in_salt_set ?saltset ;
              rdfs:label ?worktitle;
              eeboo:raw_pubplace ?place ;
              eeboo:creator ?creator .
        ?creator rdfs:label ?author .
        ?work mods:publisher ?publisherbnode .
        ?publisherbnode rdfs:label ?publisher .
        OPTIONAL {{
            ?work eeboo:precise-publication ?precisepub .
            BIND("" as ?pubDatePrecision) .
        }}
        OPTIONAL {{
            ?work eeboo:approx-publication ?approxpub .
            BIND("(approx.)" as ?pubDatePrecision) .
        }}

        BIND("Unknown" as ?pubdate).

    }} UNION {{
	SERVICE <http://emblematica.library.illinois.edu:8080/sparql> {{
		?work	bf:hasInstance	?instance ;
				bf:agent ?creator .
    ?creator rdfs:label	?author .

		?instance	bf:hasItem	?item ;
					bf:agent	?publisher ;
					bf:place	?place ;
					bf:date	?pubdate .

		OPTIONAL {{ ?item	dc:title	?worktitle . }}
	}}
}}
}}


VALUES ?workset {{
	{0}
}}

