PREFIX saltset: <http://127.0.0.1/saltsets/>
PREFIX salt: <http://127.0.0.1/salt/>
PREFIX : <http://127.0.0.1/>

select distinct ?uri ?label { 
  { 
     ?uri salt:in_salt_set saltset:eeboo_creators ; 
        rdfs:label ?label .
  }
  UNION { 
     ?uri salt:in_salt_set saltset:htrc-wcsa_creators;
        rdfs:label ?label .
     MINUS {
          ?uri :matchParticipant ?match .
          ?foo :matchParticipant ?match ; 
               salt:in_salt_set saltset:eeboo_creators . 
     } .
  }
}
